import { type ProductInput, type MarketingStrategy } from "./types"

export function generateStrategyReport(
  productInput: ProductInput,
  strategy: MarketingStrategy
): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric"
  })

  return `# Go-To-Market Strategy Report
## ${productInput.productName}

**Generated:** ${date}  
**Category:** ${productInput.productCategory}  
**Price Range:** ${productInput.priceRange}

---

## Executive Summary

This comprehensive go-to-market strategy has been generated by Product-to-Market AI to help launch and grow your product in the market.

**Product Description:**
${productInput.productDescription}

**Problem Solved:**
${productInput.problemSolved}

---

## Market Truth Analysis

**Score:** ${strategy.marketTruth.score}/10

${strategy.marketTruth.analysis}

**Recommendation:** ${strategy.marketTruth.recommendation}

---

## Target Audience

### Primary Audience
${strategy.targetAudience.primary}

### Secondary Audience
${strategy.targetAudience.secondary}

### Niche Opportunity
${strategy.targetAudience.nicheOpportunity}

**Reasoning:**
${strategy.targetAudience.reasoning}

---

## Market Segments

${strategy.productAnalysis.marketSegments.map((segment, index) => `
### ${index + 1}. ${segment.name}
- **Demographics:** ${segment.demographics}
- **Size:** ${segment.size}
- **Potential:** ${segment.potential}
`).join("\n")}

---

## Customer Persona

**Name:** ${strategy.customerPersona.name}  
**Age Group:** ${strategy.customerPersona.ageGroup}  
**Profession:** ${strategy.customerPersona.profession}  
**Lifestyle:** ${strategy.customerPersona.lifestyle}

### Motivations
${strategy.customerPersona.motivations.map(m => `- ${m}`).join("\n")}

### Pain Points
${strategy.customerPersona.painPoints.map(p => `- ${p}`).join("\n")}

### Buying Behavior
${strategy.customerPersona.buyingBehavior}

---

## Value Propositions

${strategy.productAnalysis.valuePropositions.map((prop, index) => `${index + 1}. ${prop}`).join("\n")}

---

## Launch Strategy

**Type:** ${strategy.launchStrategy.type}

${strategy.launchStrategy.description}

### Key Messaging
> "${strategy.launchStrategy.messaging}"

### Initial Campaign
${strategy.launchStrategy.initialCampaign}

---

## Marketing Channels

${strategy.marketingChannels.map(channel => `
### ${channel.name}
- **Fit:** ${channel.fit}
- **Budget:** ${channel.budget}
- **Reasoning:** ${channel.reasoning}
`).join("\n")}

---

## Budget Allocation

${strategy.budgetAllocation.map(allocation => `
### ${allocation.category} (${allocation.percentage}%)
${allocation.actions.map(action => `- ${action}`).join("\n")}
`).join("\n")}

---

## Product Lifecycle Strategy

${strategy.lifecycleStrategy.map(stage => `
### ${stage.stage}
- **Objective:** ${stage.objective}
- **Channels:** ${stage.channels.join(", ")}
- **Campaign Style:** ${stage.campaignStyle}
`).join("\n")}

---

## Customer Resistance & Solutions

${strategy.customerResistance.map((resistance, index) => `
### Barrier ${index + 1}: ${resistance.barrier}
**Solution:** ${resistance.solution}
`).join("\n")}

---

## Customer Friction Map

${strategy.customerFrictionPoints.map(point => `
### ${point.stage}
- **Friction:** ${point.friction}
- **Solution:** ${point.solution}
`).join("\n")}

---

## Strategic Warnings

${strategy.strategicWarnings.map((warning, index) => `${index + 1}. ${warning}`).join("\n")}

---

## Alternative Strategy Paths

### Path A: ${strategy.alternativeStrategies.strategyA.name}
${strategy.alternativeStrategies.strategyA.description}

**Advantages:**
${strategy.alternativeStrategies.strategyA.advantages.map(a => `- ${a}`).join("\n")}

**Risks:**
${strategy.alternativeStrategies.strategyA.risks.map(r => `- ${r}`).join("\n")}

### Path B: ${strategy.alternativeStrategies.strategyB.name}
${strategy.alternativeStrategies.strategyB.description}

**Advantages:**
${strategy.alternativeStrategies.strategyB.advantages.map(a => `- ${a}`).join("\n")}

**Risks:**
${strategy.alternativeStrategies.strategyB.risks.map(r => `- ${r}`).join("\n")}

---

## Attention Economy Strategies

${strategy.attentionStrategy.map((item, index) => `${index + 1}. ${item}`).join("\n")}

---

## Positioning Suggestions

${strategy.productAnalysis.positioningSuggestions.map((suggestion, index) => `${index + 1}. ${suggestion}`).join("\n")}

---

## Niche Opportunities

${strategy.productAnalysis.nicheOpportunities.map((opportunity, index) => `${index + 1}. ${opportunity}`).join("\n")}

---

## Demand Assumptions

${strategy.productAnalysis.demandAssumptions.map((assumption, index) => `${index + 1}. ${assumption}`).join("\n")}

---

*This report was generated by Product-to-Market AI. The strategies and recommendations are based on AI analysis and should be validated with market research and testing.*
`
}
